"""empty message

Revision ID: 19cf7ed4fdcf
Revises: 36c0c221dcc9
Create Date: 2020-10-16 03:53:19.711429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19cf7ed4fdcf'
down_revision = '36c0c221dcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quizzes_category_id_fkey', 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key('quizzes_category_id_fkey', 'quizzes', 'users', ['category_id'], ['id'])
    # ### end Alembic commands ###
