"""empty message

Revision ID: 2185506a2ec4
Revises: 
Create Date: 2020-10-15 06:21:39.718086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2185506a2ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('rating', sa.Integer(), nullable=True))
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('questions', 'rating')
    op.drop_column('categories', 'image_link')
    # ### end Alembic commands ###
