"""empty message

Revision ID: 36c0c221dcc9
Revises: 8a5b21eac089
Create Date: 2020-10-16 03:47:00.912195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c0c221dcc9'
down_revision = '8a5b21eac089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'quizzes', 'users', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.drop_column('quizzes', 'category_id')
    # ### end Alembic commands ###
