"""empty message

Revision ID: 6f071a49976c
Revises: 19cf7ed4fdcf
Create Date: 2020-10-16 03:55:48.801315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f071a49976c'
down_revision = '19cf7ed4fdcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quizzes_category_id_fkey', 'quizzes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('quizzes_category_id_fkey', 'quizzes', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
