"""empty message

Revision ID: 837cbd7e2192
Revises: 6f071a49976c
Create Date: 2020-10-16 06:16:27.967167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837cbd7e2192'
down_revision = '6f071a49976c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
